infer:
  type: "ImageFolder"
  config:
    root: "${variables.datasets_root}/kodak"
    split: "test"
  loader:
    shuffle: False
    batch_size: 1
    num_workers: 2
  settings:
  transforms:
    - "ToTensor": {}
