type: "Vimeo90kDataset"
config:
  root: "${paths.datasets}/vimeo90k/vimeo_triplet"
  split: "train"
loader:
  shuffle: True
  batch_size: 16
  num_workers: 2
settings:
  patch_size: [ 256, 256, ]
transforms:
  - "RandomCrop": {size: "${....settings.patch_size}"}
  - "ToTensor": {}
meta:
  name: "Vimeo-90K"
  identifier:
  num_samples: 153936  # = 51312 * 3
  steps_per_epoch:
