type: "ImageFolder"
config:
  root: "${paths.datasets}/clic2020-mobile"
  split: "test"
loader:
  shuffle: False
  batch_size: 1
  num_workers: 2
settings:
transforms:
  - "ToTensor": {}
meta:
  name: "CLIC 2020 Mobile"
  identifier: "image/clic2020-mobile"
  num_samples: 178
  steps_per_epoch:
