logdir: "${paths.engine}"
num_epochs: 500
valid_loader: "valid"
valid_metric: "loss"
minimize_valid_metric: True
verbose: True
check: False
callbacks:
  - type: "SchedulerCallback"
    scheduler_key: "net"
    mode: null  # "epoch" or "batch"
    loader_key: "valid"
    metric_key: "loss"
  - type: "CheckpointCallback"
    logdir: "${paths.checkpoints}"
    loader_key: "valid"
    metric_key: "loss"
    minimize: True
    mode: "runner"
    resume_runner:  "${paths.checkpoint}"
    topk: 1     # number of top-k checkpoints to keep
  - type: "EarlyStoppingCallback"
    patience: 21
    loader_key: "valid"
    metric_key: "loss"
    minimize: True
    min_delta: 1e-4  # Recommendation: < 1e-4 * {.patience}
loggers:
  aim: {}
  tensorboard:
    logdir: "${paths.tensorboard}"
