type: "ImageFolder"
config:
  root: "${paths.datasets}/clic2020-professional"
  split: "valid"
loader:
  shuffle: False
  batch_size: 64
  num_workers: 2
settings:
  patch_size: [ 256, 256, ]
transforms:
  - "CenterCrop": {size: "${....settings.patch_size}"}
  - "ToTensor": {}
meta:
  name: "CLIC 2020 Professional"
  identifier: "image/clic2020-professional"
  num_samples: 41
  steps_per_epoch:
