aim:
  repo: "${paths.aim}"
  run_hash:
git:
  compressai:
    branch:
    hash:
    main_branch: "master"
    main_hash:
  compressai_train:
    branch:
    hash:
    main_branch: "master"
    main_hash:
slurm:
  account:
  job_id:
  job_array_task_id:
  job_name:
system:
  hostname:
  username:
