aim:
  repo: "${paths.aim}"
  run_hash:
git:
  # id = f"r{commit_count}.{commit_hash}"
  # main_id = latest commit in common on main_branch
  compressai:
    branch:
    id:
    main_branch: "master"
    main_id:
  compressai_trainer:
    branch:
    id:
    main_branch: "master"
    main_id:
slurm:
  account:
  job_id:
  job_array_task_id:
  job_name:
system:
  hostname:
  username:
