_common_root:   "./logs"
_runs_root:     "${._common_root}/runs/${._run_hash}"
_aim_repo:      "main"
_run_hash:      "${env.aim.run_hash}"
datasets:       "/data/datasets"
aim:            "${._common_root}/aim/${._aim_repo}"
checkpoints:    "${._runs_root}/checkpoints"
configs:        "${._runs_root}/configs"
engine:         "${._runs_root}/engine"
src:            "${._runs_root}/src"
tensorboard:    "${._runs_root}/tensorboard"
checkpoint:     null  # to resume from checkpoint, override with e.g. "${.checkpoints}/runner.last.pth"
