_common_root:   "./logs"
_runs_root:     "${.runs_root}/${env.aim.run_hash}"  # NOTE: Deprecated.
_run_root:      "${._runs_root}"
_aim_repo:      "main"
datasets:       "/data/datasets"
runs_root:      "${._common_root}/runs"
aim:            "${._common_root}/aim/${._aim_repo}"
checkpoints:    "${._run_root}/checkpoints"
configs:        "${._run_root}/configs"
engine:         "${._run_root}/engine"
src:            "${._run_root}/src"
tensorboard:    "${._run_root}/tensorboard"
checkpoint:     null  # to resume from checkpoint, override with e.g. "${.checkpoints}/runner.last.pth"
model_checkpoint: null  # checkpoint to load only model weights from
