name: pytest

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.8"
        include:
          - os: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          poetry config installer.modern-installation false
          poetry install --with=dev,tests

      - name: Install dependencies (compressai)
        run: |
          cd ..
          git clone "https://github.com/InterDigitalInc/CompressAI.git" compressai
          cd -
          poetry run pip install -e ../compressai

      # NOTE: This could be in a separate job, but doing it here requires less computation.
      - name: Run static analysis
        run: poetry run make static-analysis

      - name: Run unit tests
        run: poetry run make tests
